#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE gitea;
	GRANT ALL PRIVILEGES ON DATABASE gitea TO $POSTGRES_USER;
	CREATE DATABASE sonar;
	GRANT ALL PRIVILEGES ON DATABASE sonar TO $POSTGRES_USER;
EOSQL